
parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  steps:
  - powershell: Test-Path ~/.nuget/packages
  - script: dotnet restore PSReadLine\PSReadLine.csproj
  - powershell: Test-Path ~/.nuget/InvokeBuild
