
parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  # Avoid expensive initialization of dotnet cli, see: http://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  steps:
  - powershell: Test-Path ~/.nuget/packages
  - script: dotnet restore PSReadLine/PSReadLine.csproj
  - powershell: Test-Path ~/.nuget/packages/InvokeBuild
